#!/usr/bin/env bash

# Read yaml tags properties in obsidian files, then
# destroy properties & insert #tags corresponding to 'tags:' properties


set -euo pipefail

output_folder=""
input_file=""

while getopts ":o:i:" option 
    do
    case "${option}" in
        o)
            output_folder="${OPTARG}"
            ;;
        i)
            input_file="${OPTARG}"
            ;;
        :)
            echo "Error : missing argument." 1>&2
            ;;
        *) 
            echo "Error: unknown option" 1>&2
            exit 1
            ;;
    esac
done

if [[ "${input_file}" == "" ]]; then
    echo "Error: no file provided" 1>&2
    exit 1
fi

if [[ "${output_folder}" == "" ]]; then
    echo "Error: no output folder provided" 1>&2
    exit 1
fi

if [[ ! -d "${output_folder}" ]]; then
    echo "${output_folder} does not exist." 1>&2
    exit 1
fi

if [[ $(ls -A "${output_folder}") ]]; then
    echo "Error: ${output_folder} must be empty." 1>&2
    exit 1
fi

if [[ ! $(command -v yq) ]]; then 
    echo "Install yq first" 1>&2
    exit 1
fi

readonly export_file="${output_folder}/${input_file#*/}"

readarray -t tags < <(
counter=0
while IFS="" read -r line || [[ -n "$p" ]]
do
  if [[ "${line}" == '---' && $counter -eq 1 ]]; then
  	break
  fi
  if [[ "${line}" == '---' && $counter -eq 0 ]]; then
  	counter=$((counter +1))
  fi
  printf '%s\n' "${line}"
done < "${input_file}" | yq '.tags[] | select(. )' )

echo "$tags"

for i in ${tags[@]}
    do
    printf '#%s ' "${i}" >> "${export_file}"
done
printf '\n\n' >> "${export_file}"

sed '/---/,/---/d' "${input_file}" >> "${export_file}"



